/**
 * build.js  -  Cloudflare Pages build script
 * ===========================================
 * Reads environment variables set in the Cloudflare Pages dashboard
 * and writes a config.js file at build time.
 *
 * This means config.js is NEVER in the git repo — secrets stay in
 * the Cloudflare environment, not in source code.
 *
 * Required environment variables (set in Cloudflare Pages dashboard):
 *   CF_API_URL                  Your Apps Script /exec URL
 *   CF_CLOUDINARY_CLOUD_NAME    Your Cloudinary cloud name
 *   CF_CLOUDINARY_UPLOAD_PRESET Your unsigned upload preset name
 *   CF_PORTAL_TOKEN             Shared secret (same as Apps Script property)
 *
 * Optional:
 *   CF_DEPT_NAME                Default: "Computer Engineering"
 *   CF_COLLEGE_NAME             Default: "Institute of Civil and Rural Engineering"
 *   CF_COLLEGE_CITY             Default: "Gargoti"
 */

const fs = require("fs");
const path = require("path");

// ── Helper ──────────────────────────────────────────────────────────────────
function requireEnv(name) {
  const val = process.env[name];
  if (!val) {
    console.error(`\n[build] ERROR: Required environment variable "${name}" is not set.`);
    console.error(`       Set it in: Cloudflare Pages > Settings > Environment variables\n`);
    process.exit(1);
  }
  return val;
}

function optionalEnv(name, defaultValue) {
  return process.env[name] || defaultValue;
}

// ── Read env vars ────────────────────────────────────────────────────────────
const config = {
  API_URL:                  requireEnv("CF_API_URL"),
  CLOUDINARY_CLOUD_NAME:    requireEnv("CF_CLOUDINARY_CLOUD_NAME"),
  CLOUDINARY_UPLOAD_PRESET: requireEnv("CF_CLOUDINARY_UPLOAD_PRESET"),
  PORTAL_TOKEN:             requireEnv("CF_PORTAL_TOKEN"),
  LOGO:                     "logo.png",
  ADMIN_URL:                "admin.html",
  STUDENT_PORTAL_URL:       "index.html",
  DEPT_NAME:                optionalEnv("CF_DEPT_NAME",    "Computer Engineering"),
  COLLEGE_NAME:             optionalEnv("CF_COLLEGE_NAME", "Institute of Civil and Rural Engineering"),
  COLLEGE_CITY:             optionalEnv("CF_COLLEGE_CITY", "Gargoti"),
};

// ── Validate API URL looks legitimate ────────────────────────────────────────
if (!config.API_URL.startsWith("https://script.google.com/")) {
  console.warn("[build] WARNING: CF_API_URL doesn't look like a Google Apps Script URL.");
}

// ── Generate config.js ───────────────────────────────────────────────────────
const output = `/**
 * config.js — AUTO-GENERATED at build time by build.js
 * Do NOT edit this file. Edit environment variables in Cloudflare Pages.
 * Generated: ${new Date().toISOString()}
 */
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

const outPath = path.join(__dirname, "config.js");
fs.writeFileSync(outPath, output, "utf8");

console.log("[build] config.js generated successfully.");
console.log(`[build]   API_URL:       ${config.API_URL.slice(0, 48)}...`);
console.log(`[build]   Cloud name:    ${config.CLOUDINARY_CLOUD_NAME}`);
console.log(`[build]   Preset:        ${config.CLOUDINARY_UPLOAD_PRESET}`);
console.log(`[build]   Token:         ${"*".repeat(config.PORTAL_TOKEN.length)}`);
console.log("[build] Done. Deploy output directory: . (project root)");
